version: 0.2

env:
  variables:
    TFDIR: "environments"
    TFNCONF: "codebuild/tfnotify.yml"
    TITLE: "Terraform Apply"
    MSG: "Apply detail via tfnotify"

phases:
  install:
    commands:
      # terraform
      - curl -sL https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip > terraform.zip
      - unzip terraform.zip
      - cp terraform /usr/local/bin
      # tfnotify
      - curl -sL https://github.com/mercari/tfnotify/releases/download/v0.8.0/tfnotify_linux_amd64.tar.gz > tfnotify.tar.gz
      - tar -zxvf tfnotify.tar.gz
      - cp tfnotify /usr/local/bin
  pre_build:
    commands:
      - echo "terraform init"
      - terraform -chdir="${TFDIR}" init -input=false -no-color
  build:
    commands:
      - echo "terraform apply"
      - echo "TFDIR:${TFDIR}"
      - echo "TFNCONF:${TFNCONF}"
      - echo "TITLE:${TITLE}"
      - echo "MSG:${MSG}"
      - |
        APPLY=$(terraform -chdir="${TFDIR}" apply -input=false -no-color 2>&1)
        echo "${APPLY}" | tfnotify --config "${TFNCONF}" apply --title "${TITLE}" --message "${MSG}"
